name: "git-clang-format check per commit"
description: "Check each commit for proper format individually and don't allow format fixups"
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  target-ref:
    description: 'The target ref to find a merge base with'
    required: true
  source-ref:
    description: 'The source ref to check commits from. HEAD if omitted'
    required: false
    default: HEAD
  clang-version:
    description: 'The version of clang-format to use (3.9 to 12)'
    required: false
    default: 12
  fetch-depth:
    description: 'Fetch depth for git (default: 50)'
    required: false
    default: 50

runs:
  using: "docker"
  image: "docker://wolletd/clang-format:latest"
  env:
    SOURCE_REF: ${{ inputs.source-ref }}
    FETCH_DEPTH: ${{ inputs.fetch-depth }}
    CLANG_VERSION: ${{ inputs.clang-version }}
  args:
    - ${{ inputs.target-ref }}
