name: Build Docker Image

on:
  push:
    branches: [ master ]

env:
  DOCKER_BUILDKIT: 1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v2
      - name: Build the image
        run: docker build . --build-arg UID=$(id -u) --tag wolletd/clang-format:latest
      - name: Build the rooted image
        run: docker build . --target root --build-arg UID=$(id -u) --tag wolletd/clang-format:root
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the image
        run: docker push wolletd/clang-format:latest
      - name: Push the rooted image
        run: docker push wolletd/clang-format:root
