name: Build Docker Image

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v2
      - name: Build the image
        run: docker build . --tag wolletd/clang-format:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the image
        run: docker push wolletd/clang-format:latest
