name: Build Test Image

on: [ pull_request ]

env:
  SHOW_SKIPPED: 1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v2
      - name: Build the image
        run: docker build . --build-arg UID=$(id -u) --tag wolletd/clang-format:test
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the image
        run: docker push wolletd/clang-format:test
  tests-standalone:
    strategy:
      matrix:
        target: [ master, 478faddd4a1471a574573d556491d8b14a2f2f5c ]
        src-ok: [ testdata, test/data1, 5d839740ac4bcc3de80980b5f6447ec1cfbf3832 ]
        include:
          - src-ok: testdata
            src-err: testdata2
          - src-ok: test/data1
            src-err: test/data2
          - src-ok: 5d839740ac4bcc3de80980b5f6447ec1cfbf3832
            src-err: d0c66c69a10caa195b4b46b0d95e48c0348a2e74
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: test with no error
        uses: wolletd/clang-format-checker@test
        with:
          source-ref: ${{ matrix.src-ok }}
          target-ref: ${{ matrix.target }}
      - name: test json is skipped
        uses: wolletd/clang-format-checker@test
        with:
          source-ref: ${{ matrix.src-ok }}
          target-ref: ${{ matrix.target }}
          clang-version: 12
      - name: test with format error
        uses: wolletd/clang-format-checker@test
        with:
          source-ref: ${{ matrix.src-err }}
          target-ref: ${{ matrix.target }}
        continue-on-error: true
        id: fail1
      - name: test with git error
        uses: wolletd/clang-format-checker@test
        with:
          source-ref: ${{ matrix.src-ok }}
          target-ref: nonexistent
        continue-on-error: true
        id: fail2
      - name: check for expected failures
        if: steps.fail1.outcome == 'success' || steps.fail2.outcome == 'success'
        run: exit 1
  tests-checkout:
    strategy:
      matrix:
        target: [ master, 478faddd4a1471a574573d556491d8b14a2f2f5c ]
        src-ok: [ testdata, test/data1, 5d839740ac4bcc3de80980b5f6447ec1cfbf3832 ]
        include:
          - src-ok: testdata
            src-err: testdata2
          - src-ok: test/data1
            src-err: test/data2
          - src-ok: 5d839740ac4bcc3de80980b5f6447ec1cfbf3832
            src-err: d0c66c69a10caa195b4b46b0d95e48c0348a2e74
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: checkout ${{ matrix.src-ok }}
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.src-ok }}
      - name: test with no error
        uses: wolletd/clang-format-checker@test
        with:
          target-ref: ${{ matrix.target }}
      - name: test json is skipped
        uses: wolletd/clang-format-checker@test
        with:
          target-ref: ${{ matrix.target }}
          clang-version: 12
      - name: test with git error
        uses: wolletd/clang-format-checker@test
        with:
          target-ref: nonexistent
        continue-on-error: true
        id: fail2
      - name: checkout ${{ matrix.src-err }}
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.src-err }}
      - name: test with format error
        uses: wolletd/clang-format-checker@test
        with:
          target-ref: ${{ matrix.target }}
        continue-on-error: true
        id: fail1
      - name: check for expected failures
        if: steps.fail1.outcome == 'success' || steps.fail2.outcome == 'success'
        run: exit 1
  tests-wrapper:
    runs-on: ubuntu-latest
    needs: docker
    env:
      CFC_DOCKER_IMAGE: wolletd/clang-format:test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: fetch required refs
        run: git fetch --depth=50 origin master:master tag testdata tag testdata2
      - name: test with no error
        run: ./clang-format-checker master testdata
      - name: test json is skipped
        run: ./clang-format-checker -v12 master testdata
      - name: test with git error
        run: '! ./clang-format-checker nonexistent testdata'
      - name: test with format error
        run: '! ./clang-format-checker master testdata2'
