name: Build Test Image

on: [ pull_request ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v2
      - name: Build the image
        run: docker build . --tag wolletd/clang-format:test
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the image
        run: docker push wolletd/clang-format:test
  tests:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: test with no error
        uses: wolletd/clang-format-checker@test
        with:
          source-ref: testdata
          target-ref: master
      - name: test json is skipped
        uses: wolletd/clang-format-checker@test
        with:
          source-ref: testdata
          target-ref: master
          clang-version: 12
      - name: test with format error
        uses: wolletd/clang-format-checker@test
        with:
          source-ref: testdata2
          target-ref: master
        continue-on-error: true
        id: fail1
      - name: test with git error
        uses: wolletd/clang-format-checker@test
        with:
          source-ref: testdata
          target-ref: nonexistent
        continue-on-error: true
        id: fail2
      - name: check for expected failures
        if: steps.fail1.outcome == 'success' || steps.fail2.outcome == 'success'
        run: exit 1
  tests-checkout:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: checkout testdata
        uses: actions/checkout@v2
        with:
          ref: testdata
      - name: test with no error
        uses: wolletd/clang-format-checker@test
        with:
          target-ref: master
      - name: test json is skipped
        uses: wolletd/clang-format-checker@test
        with:
          target-ref: master
          clang-version: 12
      - name: test with git error
        uses: wolletd/clang-format-checker@test
        with:
          target-ref: nonexistent
        continue-on-error: true
        id: fail2
      - name: checkout testdata2
        uses: actions/checkout@v2
        with:
          ref: testdata2
      - name: test with format error
        uses: wolletd/clang-format-checker@test
        with:
          target-ref: master
        continue-on-error: true
        id: fail1
      - name: check for expected failures
        if: steps.fail1.outcome == 'success' || steps.fail2.outcome == 'success'
        run: exit 1
